[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#e78a4e"
index = 16

[[colors.indexed_colors]]
color = "#c14a4a"
index = 17

[colors.bright]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'
# black = '#7c6f64'
# red = '#ea6962'
# green = '#a9b665'
# yellow = '#d8a657'
# blue = '#7daea3'
# magenta = '#d3869b'
# cyan = '#89b482'
# white = '#d4be98'

[colors.normal]
black = '#414b50'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'
# black = '#1D2021'
# red = '#ea6962'
# green = '#a9b665'
# yellow = '#d8a657'
# blue = '#7daea3'
# magenta = '#d3869b'
# cyan = '#89b482'
# white = '#d4be98'

[colors.dim]
black = '#414b50'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'
# black = '#1D2021'
# red = '#ea6962'
# green = '#a9b665'
# yellow = '#d8a657'
# blue = '#7daea3'
# magenta = '#d3869b'
# cyan = '#89b482'
# white = '#d4be98'

[colors.selection]
text = "#1E1E2E"       # base
background = "#F5E0DC" # rosewater

[colors.hints.start]
foreground = "#1E1E2E" # base
background = "#F9E2AF" # yellow

[colors.hints.end]
foreground = "#1E1E2E" # base
background = "#A6ADC8" # subtext0

[colors.search.matches]
foreground = "#1E1E2E" # base
background = "#A6ADC8" # subtext0

[colors.search.focused_match]
foreground = "#1E1E2E" # base
background = "#A6E3A1" # green

[colors.cursor]
text = "#1E1E2E"   # base
cursor = "#F5E0DC" # rosewater

[colors.primary]
# background= '#272e33'
foreground = '#d3c6aa'
background = "#0F0F11" # base
# foreground = "#d4be98" # text
dim_foreground = "#CDD6F4"    # text
bright_foreground = "#CDD6F4" # text

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "Victor Mono"
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[scrolling]
history = 100000
multiplier = 3

[shell]
program = "/usr/local/bin/tmux"

[window]
decorations = "none"
opacity = 1.0
startup_mode = "Maximized"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 5
y = 5
