general.import = [
    # "~/.config/alacritty/everforest.toml",
    "~/.config/alacritty/gruvbox_material.toml",
    # "~/.config/alacritty/ayu.toml",
    # "~/.config/alacritty/gruvbox_material_hard_dark.toml",
]

[terminal.shell]
program = "/home/rabeta/.nix-profile/bin/tmux"

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
startup_mode = "Maximized"
padding = { x = 10, y = 10 }

[scrolling]
history = 100000
multiplier = 3

[font]
size = 11.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "Victor Mono"
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = true

[cursor.style]
blinking = "Always"
shape = "Block"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Return"
mods = "Alt"
