# Setting the prefix from C-b to C-a
unbind C-b
set -g prefix C-a

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# Make 24bit color works
set -ga terminal-overrides ",xterm-256color:Tc"
