# bnsCreate
PUT /bns_api/bnsSessionsDate/bnsCreate?key={{KEY}} HTTP/1.1
Host: 0.0.0.0:8080
Accept: application/json
Content-Type: application/json
Content-Length: 98

{
    "name":"ACAD - Actuariat en assurance non-vie",
    "debut":"2024-10-05",
    "fin":"2024-10-05",
    "date_start":"2024-10-05 09:00:00",
    "duree":"7",
    "bns_sessionsdate_ville_c":"Paris",
    "horairemat1":"09:00:00",
    "horairemat2":"13:00:00",
    "horaireapm1":"14:00:00",
    "horaireapm2":"17:00:00",
    "unit":"H",
    "account_id_c":"",
    "session_id" : "a9356822-2563-11ee-800e-0050569693d1"
}

# bnsCreateUpdate
PUT /bns_api/bnsSessionsDate/bnsCreateUpdate?key={{KEY}} HTTP/1.1
Host: {{HOST}}
Accept: application/json
Content-Type: application/json
Content-Length: 148

{
    "id":"338f078c-5230-11ee-baf9-005056968f20",
    "name":"ACAD - Actuariat en assurance non-vie",
    "debut":"2024-10-05",
    "fin":"2024-10-05",
    "date_start":"2024-10-05 09:00:00",
    "duree":"7",
    "bns_sessionsdate_ville_c":"Paris",
    "horairemat1":"09:00:00",
    "horairemat2":"13:00:00",
    "horaireapm1":"14:00:00",
    "horaireapm2":"17:00:00",
    "unit":"H",
    "account_id_c":"",
    "session_id" : "a9356822-2563-11ee-800e-0050569693d1"
}
