# bnsHelp
GET {{HOST}}/bns_api/bnsSessions/bnsHelp?key={{KEY}}

# getRelatedModulesInfo   
GET {{HOST}}/index.php?key={{KEY}}&entryPoint=bnsWebServiceSessionCapture&bns_action=getRelatedModulesInfo&id=c7e8f900-3da0-11ee-8b2a-0050569c7b60
GET {{HOST}}/index.php?key={{KEY}}&entryPoint=bnsWebServiceSessionCapture&bns_action=getRelatedModulesInfo&id=c7e8f900-3da0-11ee-8b2a-0050569c7b60&related_modules=bns_products,contacts
GET {{HOST}}/bns_api/bnsSessions/bnsRelatedModulesInfo?key={{KEY}}&id=ed6e6cca-ac3f-11ed-b197-0050569c7b60&related_modules=bns_products,contacts

# bnsCreate
PUT {{HOST}}/bns_api/bnsSessions/bnsCreate?key={{KEY}}
Content-Type: application/json

{
  "name": "AJOCJ - La buena que te caga l’organisation des jurifdsfdsdictions etfdsfdsfsdfdsfdsfdsfs connaître les délais de prescription",
  "id": "",
  "bnsproduct_id": "efc00d88-49d3-11eb-a00d-0050569c6b80",
  "debut": "2023-01-01",
  "fin": "2023-01-01",
  "status": "prepared",
  "modalitemo": "elearning",
  "bnstype": "inter",
  "bns_session_catstat_c": "inter",
  "modaliteorg": "plein",
  "intitule": "ACOJC - Comprendre l’organisation des juridictions et connaître les délais de prescription",
  "eventtype": "training",
  "dates": {
    "1": {
      "name": "AJOCJ - Te saliste l’organisation des juridictions et connaître les délais de prescription",
      "debut": "2024-01-02",
      "fin": "2024-01-11",
      "date_start": "2024-01-02 09:00:00",
      "duree": "7",
      "bns_sessionsdate_ville_c": "Agen",
      "horairemat1": "09:00:00",
      "horairemat2": "13:00:00",
      "horaireapm1": "14:00:00",
      "horaireapm2": "17:00:00",
      "unit": "H",
      "account_id_c": ""
    }
  }
}


# bnsCreateUpdate
PUT {{HOST}}/bns_api/bnsSessions/bnsCreateUpdate?key={{KEY}}
Content-Type: application/json

{
  "name": "AJOCJ - La buena que te caga l’organisation des jurifdsfdsdictions etfdsfdsfsdfdsfdsfdsfs connaître les délais de prescription",
  "id": "bb651586-64df-11ee-a509-0242ac1e0004",
  "bnsproduct_id": "efc00d88-49d3-11eb-a00d-0050569c6b80",
  "debut": "2023-01-01",
  "fin": "2023-01-01",
  "status": "prepared",
  "modalitemo": "elearning",
  "bnstype": "inter",
  "bns_session_catstat_c": "inter",
  "modaliteorg": "plein",
  "intitule": "ACOJC - Comprendre l’organisation des juridictions et connaître les délais de prescription",
  "eventtype": "training",
  "dates": {
    "1": {
      "name": "AJOCJ - Te saliste l’organisation des juridictions et connaître les délais de prescription",
      "debut": "2024-01-02",
      "fin": "2024-01-11",
      "date_start": "2024-01-02 07:00:00",
      "duree": "7",
      "bns_sessionsdate_ville_c": "Agen",
      "horairemat1": "09:00:00",
      "horairemat2": "13:00:00",
      "horaireapm1": "14:00:00",
      "horaireapm2": "17:00:00",
      "unit": "H",
      "account_id_c": ""
    }
  }
}

