alias zshconfig="vi ~/.zshrc"
alias ohmyzsh="vi ~/.oh-my-zsh"
alias sc="symfony console"
alias devil="cd devilbox/"
alias dcupd="docker-compose up -d php mysql httpd bind"
alias dv="devil && dcupd && cd && c"
alias dvs="cd && devil && dcstop && dcrm -f && cd && c"
alias c="clear"
alias po="poweroff"
alias rb="reboot"
alias unity="cd && cd games/ && ./UnityHub.AppImage"
alias python="/usr/bin/python3.9"
alias gitt="git log --graph --pretty=oneline --abbrev-commit"
alias tor="cd && cd tor-browser-linux64-10.0.8_en-US/tor-browser_en-US/ && ./start-tor-browser.desktop"
