# Spaceship config
# prompt
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
SPACESHIP_PROMPT_PREFIXES_SHOW=true
# execution time
SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_EXEC_TIME_PREFIX=" "
SPACESHIP_EXEC_TIME_SUFFIX=""
# user
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_PREFIX="["
SPACESHIP_USER_SUFFIX="@]"
# host
SPACESHIP_HOST_SHOW=false
# directory
SPACESHIP_DIR_SHOW=true
SPACESHIP_DIR_PREFIX=" "
SPACESHIP_DIR_SUFFIX=""
SPACESHIP_DIR_TRUNC=3
# git
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_PREFIX=" "
SPACESHIP_GIT_SUFFIX=""
# git branch
SPACESHIP_GIT_BRANCH_SHOW=true
# git status
SPACESHIP_GIT_STATUS_SHOW=true
# mercurial
SPACESHIP_HG_SHOW=false
# mercurial branch
SPACESHIP_HG_BRANCH_SHOW=false
# mercurial status
SPACESHIP_HG_STATUS_SHOW=false
# package
SPACESHIP_PACKAGE_SHOW=false
# node.js
SPACESHIP_NODE_SHOW=false
# php
SPACESHIP_PHP_SHOW=true
SPACESHIP_PHP_PREFIX=" "
SPACESHIP_PHP_SUFFIX=""
# rust
SPACESHIP_RUST_SHOW=true
SPACESHIP_RUST_PREFIX=" "
SPACESHIP_RUST_SUFFIX=""
# pyenv
SPACESHIP_PYENV_SHOW=true
SPACESHIP_PYENV_PREFIX=" "
SPACESHIP_PYENV_SUFFIX=""
# docker
SPACESHIP_DOCKER_SHOW=true
SPACESHIP_DOCKER_PREFIX=" "
SPACESHIP_DOCKER_SUFFIX=""

